# Start by building the application.
FROM golang:1.20.5-alpine3.18 as build

RUN apk add nodejs-current npm gcc alpine-sdk

WORKDIR /go/src/app
COPY . .

RUN cd web/blog \
	&& npm install \
	&& npm run build \
	&& cd -

RUN go mod tidy \
	&& CGO_ENABLED=1 go build -o /go/bin/app

# Now copy it into a smaller alpine image
FROM alpine:3.18
COPY --from=build /go/bin/app /
CMD ["/app"]
