# We chose bullseye == debian11 so we have the same libc as distroless/base-debian1
# Otherwise by using the default golang:1.20 image we would get
# docker run --rm blogomatic:distroless-multistage
# /app: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /app)

# Start by building the application.
FROM golang:1.20.5-bullseye as build
WORKDIR /tmp
RUN curl -sL https://deb.nodesource.com/setup_18.x -o nodesource_setup.sh \
	&& bash nodesource_setup.sh \
	&& rm nodesource_setup.sh \
	&& apt-get install -y nodejs --no-install-recommends

WORKDIR /go/src/app
COPY . .

WORKDIR /go/src/app/web/blog
RUN rm -rf build node_modules \
	&& npm install \
	&& npm run build 

WORKDIR /go/src/app
RUN rm -rf bin \
	&& go mod tidy \
	&& go build -o /go/bin/app

# Now copy it into our base image.
FROM gcr.io/distroless/base-debian11:debug-nonroot
WORKDIR /
COPY --from=build /go/bin/app /
ENTRYPOINT ["/app"]
